# $Id: Makefile 564 2005-10-06 06:49:43Z quarl $

include ~/lib/make/Makefile.rest2html

REST_FLAGS = --last-modified --footer-kc --stylesheet-kc --footnote-references=superscript --trim-footnote-reference-space

REST_STYLESHEET = style.css
